### ISSUE TITLE
I can edit content using the sidebar and see changes on save (Sidebar/ edit mode)

### ISSUE THREAD

**Issue by djay** [collective/volto-hydra#2]
# User Stories (as an editor...)
- [x] #13
- [x] #15
- [x] #17
- [x] #18
- [ ] #14
- [x] #16
- [x] #19
- [x] #69
- [ ] #77
- [x] I can Move a block in a page from the sidepanel using blocks tree nav (https://github.com/plone/volto/issues/4757)
- [x] I can Lock content which I am editing so there’s no clashing with other users.
- [x] I can Click on workflow Publish button to make the page public
- [ ] #55

## Out of scope
- [ ] I can Add a new  block front the sidepanel blocks nav tree and edit it (https://github.com/plone/volto/issues/4757)

# Technical
- ‘Central’ storage for data (to be shared between sidebar and page contents)
    - Needs to account for both block data and content type/ page data
    - Blocks need proper schema and all fields to appear

**Comment by djay** [comment]
@MAX-786 at this stage we don't need the iframe bridge. You can just reload the whole page in iframe after save.

Later on with the iframe bridge this can be done by the frontend recieving a message that the page is saved and it can reload itself instead.
