### ISSUE TITLE
I can manage blocks inside the preview (quanta toolbar)

### ISSUE THREAD

**Issue by djay** [collective/volto-hydra#4]
![Image](https://github.com/collective/volto-hydra/assets/41700/a38b0919-44ad-4d3a-96b8-da08cab95b9a)

# User stories (As an editor...)
- [x] #23
- [x] #24
- [x] #25
- [x] #26
- [x] #27
- [x] #70

## Out of scope
- [ ] #81
- [ ] #65
- [ ] #67
- [ ] I can Click on Undo/redo button to reverse the changes just made 
- [ ] #104
- [ ] I can Select multiple blocks at once (inline) so I can move them inside a container. (does Volto support this now?)
- [ ] I can select multiple blocks using text selection
- [ ] #82
- [ ] I can add blocks before and after using the quanta toolbar menu
- [ ] #113
- [ ] I can see a single line highlight for text only style blocks

# Technical
- Communicating from the iFrame bridge to the admin UI
- Keeping block locations stored- for selection/showing UI
- Painting inside of the iFrame (block selection border) for simple things that stay during scroll
- Painting ontop-outside of the iFrame (quanta toolbar) and hiding them during scroll

**Comment by djay** [comment]
I split the container stuff into a seperate epic in #99. It's really a whole seperate thing to deal with
